version: '3.9'

services:
  s3minio:
    ports:
    - 9000:9000
    - 9001:9001
    image: minio/minio:RELEASE.2023-02-17T17-52-43Z.fips
    command: server /data --console-address ":9001"
  
  s3minio-slave:
    ports:
    - 8000:9000
    - 8001:9001
    image: minio/minio:RELEASE.2023-02-17T17-52-43Z.fips
    command: server /data --console-address ":9001"

  grafana:
    image: grafana/grafana:9.3.0
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/datasources.yaml:/home/adam/Documents/zminio/docker/datasources.yaml

  prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - 9090:9090
    volumes:
      - /home/adam/Documents/zminio/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml