{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zsync_uptime", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "sync status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "zminio_sync_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "upload and download",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zminio_zminio_download", "legendFormat": "__auto" },
    { "expr": "zminio_zminio_upload", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "download count",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zminio_zminio_download", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "upload count",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zminio_zminio_upload", "legendFormat": "__auto" }
   ]
  }
 ]
}